const state={map:null,routeLayer:null,cameraLayer:null};const api=(path)=>fetch(path).then(r=>{if(!r.ok)throw Error('request failed');return r.json()});const formatTime=(v)=>new Date(v).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});
function icon(color){return L.divIcon({className:'camera-marker',html:`<span style="display:block;width:14px;height:14px;border:3px solid white;border-radius:50%;background:${color};box-shadow:0 2px 8px #17232166"></span>`,iconSize:[14,14],iconAnchor:[7,7]})}
function initMap(cameras){state.map=L.map('map',{zoomControl:false}).setView([28.622,77.217],14);L.control.zoom({position:'bottomright'}).addTo(state.map);L.tileLayer('https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png',{attribution:'&copy; OpenStreetMap &copy; CARTO'}).addTo(state.map);state.cameraLayer=L.layerGroup().addTo(state.map);cameras.forEach(c=>L.marker([c.latitude,c.longitude],{icon:icon(c.status==='warning'?'#f5a623':'#0d756b')}).bindPopup(`<strong>${c.name}</strong><br>${c.camera_id}<br><small>${c.status.toUpperCase()}</small>`).addTo(state.cameraLayer))}
function renderMetrics(a){const items=[['TOTAL SIGHTINGS',a.total_sightings,'across camera network'],['UNIQUE VEHICLES',a.unique_vehicles,'tracked today'],['BLACKLIST MATCHES',a.blacklist_matches,'require attention'],['CAMERA NODES',a.by_camera.length,'active in demo']];document.querySelector('#metrics').innerHTML=items.map(x=>`<div class="metric"><div class="metric-label">${x[0]}</div><div class="metric-value">${x[1]}</div><div class="metric-note">${x[2]}</div></div>`).join('')}
function renderCameras(cameras,a){const stats=Object.fromEntries(a.by_camera.map(x=>[x.camera_id,x]));document.querySelector('#camera-table').innerHTML='<div class="camera-row header"><span>NODE</span><span>STATUS</span><span>VEHICLES</span><span>CONFIDENCE</span></div>'+cameras.map(c=>{const s=stats[c.camera_id];return `<div class="camera-row"><span class="camera-name">${c.name}<small>${c.camera_id} / ${c.direction}</small></span><span class="${c.status}">${c.status}</span><span>${s.unique_vehicles}</span><span>${Math.round(s.average_confidence*100)}%</span></div>`}).join('')}
function renderAlerts(alerts){document.querySelector('#alert-count').textContent=alerts.length;document.querySelector('#alerts').innerHTML=alerts.length?alerts.map(a=>`<div class="alert ${a.severity==='high'?'high':''}"><span class="alert-bar"></span><div><strong>${a.plate}</strong><small>${a.reason} / ${a.camera_id}</small></div><span class="alert-time">${formatTime(a.detected_at)}</span></div>`).join(''):'<p class="hint">No active alerts.</p>'}
function renderRoutes(routes){document.querySelector('#routes').innerHTML=routes.map(x=>`<div class="route-row"><span>${x.route}</span><strong>${x.count} transitions</strong></div>`).join('')}
async function showTrajectory(plate){try{const result=await api(`/api/vehicles/${encodeURIComponent(plate.trim().toUpperCase())}/trajectory`);if(state.routeLayer)state.routeLayer.remove();const points=result.events.map(e=>[e.latitude,e.longitude]);state.routeLayer=L.polyline(points,{color:'#f06b50',weight:5,opacity:.9}).addTo(state.map);points.forEach((p,i)=>L.circleMarker(p,{radius:7,color:'#fff',weight:3,fillColor:'#f06b50',fillOpacity:1}).bindTooltip(`${i+1}. ${result.events[i].camera_id} / ${formatTime(result.events[i].detected_at)}`).addTo(state.routeLayer));state.map.fitBounds(state.routeLayer.getBounds(),{padding:[45,45]});document.querySelector('#trajectory-summary').innerHTML=`<strong>${result.plate}</strong><span>${result.point_count} camera sightings / route reconstructed</span>`}catch{document.querySelector('#trajectory-summary').innerHTML='<strong>Plate not found</strong><span>Try one of the sample registrations below.</span>'}}
async function boot(){const [cameras,analytics,alerts]=await Promise.all([api('/api/cameras'),api('/api/analytics'),api('/api/alerts')]);initMap(cameras);renderMetrics(analytics);renderCameras(cameras,analytics);renderAlerts(alerts);renderRoutes(analytics.routes);await showTrajectory(document.querySelector('#plate-input').value);document.querySelector('#service-status').textContent='System online'}
document.querySelector('#search-form').addEventListener('submit',e=>{e.preventDefault();showTrajectory(document.querySelector('#plate-input').value)});document.querySelectorAll('.plate-link').forEach(b=>b.addEventListener('click',()=>{document.querySelector('#plate-input').value=b.dataset.plate;showTrajectory(b.dataset.plate)}));boot().catch(()=>{document.querySelector('#service-status').textContent='Service unavailable'});
